source 'https://rubygems.org'

gem 'sinatra', '~> 1.4.7'
gem 'rack_csrf', '~> 2.5.0'
gem 'require_all'


gem 'rgl', '~> 0.5.2'
gem 'rerun', '~> 0.11.0'
gem 'rake', '~> 10.4.0'


# same as in catalog_scraper
gem 'mongo', '~> 2.2.5' # using Mongo 2.6
