catalog_scraper_gemfile_path =
	File.expand_path(
		File.join(
			File.dirname(__FILE__), '..', 'catalog_scraper', 'Gemfile'
		)
	)

eval(IO.read(catalog_scraper_gemfile_path), binding)
# NOTE: eval() is for Ruby-level evaluaton. exec() is for shell.


gem 'sinatra', '~> 1.4.7'
gem 'rack_csrf', '~> 2.5.0'
