source 'https://rubygems.org'

gem 'sinatra', '~> 1.4.7'
gem 'rack_csrf', '~> 2.5.0'
gem 'require_all'


# same as in catalog_scraper
gem 'mongo', '~> 2.2.5' # using Mongo 2.6
gem 'activerecord', '4.2.6'
